# The ArgoCD Application for all Crossplane Managed Resources
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: my-custom-app
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
spec:
    project: default
    source:
        repoURL: https://github.com/salvamiguel/crossplane-iac-example
        targetRevision: HEAD
        path: infrastructure
    destination:
        namespace: default
        server: https://kubernetes.default.svc
    syncPolicy:
        automated:
            prune: true
        retry:
            limit: 5
            backoff:
                duration: 5s
                factor: 2
                maxDuration: 1m
